// Genere CLQ App Factory v2026.07.26-culture-city-bound
const locations=[
    { name: "Cathédrale Saint-Bavon et Agneau Mystique", lat: 51.053238, lng: 3.7265, audio: "audio/Cathedrale_Saint_Bavon_et_Agneau_Mystique.mp3", image: "images/points interets/cathedrale-saint-bavon-et-agneau-mystique.jpg", fallbackImage: "images/points interets/Cathedrale_Saint_Bavon_et_Agneau_Mystique.svg" },
    { name: "Beffroi, Halle aux draps et Mammelokker", lat: 51.053682, lng: 3.725014, audio: "audio/Beffroi_Halle_aux_draps_et_Mammelokker.mp3", image: "images/points interets/beffroi-halle-aux-draps-et-mammelokker.jpg", fallbackImage: "images/points interets/Beffroi_Halle_aux_draps_et_Mammelokker.svg" },
    { name: "Hôtel de Ville de Gand", lat: 51.054479, lng: 3.725266, audio: "audio/Hotel_de_Ville_de_Gand.mp3", image: "images/points interets/hotel-de-ville-de-gand.jpg", fallbackImage: "images/points interets/Hotel_de_Ville_de_Gand.svg" },
    { name: "Korenmarkt et église Saint-Nicolas", lat: 51.054122, lng: 3.721994, audio: "audio/Korenmarkt_et_eglise_Saint_Nicolas.mp3", image: "images/points interets/korenmarkt-et-eglise-saint-nicolas.jpg", fallbackImage: "images/points interets/Korenmarkt_et_eglise_Saint_Nicolas.svg" },
    { name: "Pont Saint-Michel", lat: 51.053886, lng: 3.72054, audio: "audio/Pont_Saint_Michel.mp3", image: "images/points interets/pont-saint-michel.jpg", fallbackImage: "images/points interets/Pont_Saint_Michel.svg" },
    { name: "Graslei et Korenlei", lat: 51.054904, lng: 3.720235, audio: "audio/Graslei_et_Korenlei.mp3", image: "images/points interets/graslei-et-korenlei.jpg", fallbackImage: "images/points interets/Graslei_et_Korenlei.svg" },
    { name: "Château des Comtes", lat: 51.057183, lng: 3.720717, audio: "audio/Chateau_des_Comtes.mp3", image: "images/points interets/chateau-des-comtes.jpg", fallbackImage: "images/points interets/Chateau_des_Comtes.svg" },
    { name: "Vrijdagmarkt et Jacob van Artevelde", lat: 51.05701, lng: 3.725529, audio: "audio/Vrijdagmarkt_et_Jacob_van_Artevelde.mp3", image: "images/points interets/vrijdagmarkt-et-jacob-van-artevelde.jpg", fallbackImage: "images/points interets/Vrijdagmarkt_et_Jacob_van_Artevelde.svg" },
    { name: "Portus Ganda et confluence", lat: 51.053886, lng: 3.734027, audio: "audio/Portus_Ganda_et_confluence.mp3", image: "images/points interets/portus-ganda-et-confluence.jpg", fallbackImage: "images/points interets/Portus_Ganda_et_confluence.svg" },
    { name: "Château de Gérard le Diable", lat: 51.052009, lng: 3.728422, audio: "audio/Chateau_de_Gerard_le_Diable.mp3", image: "images/points interets/chateau-de-gerard-le-diable.jpg", fallbackImage: "images/points interets/Chateau_de_Gerard_le_Diable.svg" },
    { name: "Ruelle aux graffitis — Werregarenstraat", lat: 51.055491, lng: 3.724633, audio: "audio/Ruelle_aux_graffitis_Werregarenstraat.mp3", image: "images/points interets/ruelle-aux-graffitis-werregarenstraat.jpg", fallbackImage: "images/points interets/Ruelle_aux_graffitis_Werregarenstraat.svg" },
    { name: "Prinsenhof et mémoire de Charles Quint", lat: 51.05922, lng: 3.717145, audio: "audio/Prinsenhof_et_memoire_de_Charles_Quint.mp3", image: "images/points interets/prinsenhof-et-memoire-de-charles-quint.jpg", fallbackImage: "images/points interets/Prinsenhof_et_memoire_de_Charles_Quint.svg" },
    { name: "Patershol", lat: 51.057994, lng: 3.723483, audio: "audio/Patershol.mp3", image: "images/points interets/patershol.jpg", fallbackImage: "images/points interets/Patershol.svg" },
    { name: "Église Saint-Jacques et Bij Sint-Jacobs", lat: 51.056616, lng: 3.728259, audio: "audio/Eglise_Saint_Jacques_et_Bij_Sint_Jacobs.mp3", image: "images/points interets/eglise-saint-jacques-et-bij-sint-jacobs.jpg", fallbackImage: "images/points interets/Eglise_Saint_Jacques_et_Bij_Sint_Jacobs.svg" },
    { name: "Citadelpark", lat: 51.03762, lng: 3.72126, audio: "audio/Citadelpark.mp3", image: "images/points interets/citadelpark.jpg", fallbackImage: "images/points interets/Citadelpark.svg" },
    { name: "STAM et site de la Bijloke", lat: 51.04489, lng: 3.71634, audio: "audio/STAM_et_site_de_la_Bijloke.mp3", image: "images/points interets/stam-et-site-de-la-bijloke.jpg", fallbackImage: "images/points interets/STAM_et_site_de_la_Bijloke.svg" },
    { name: "Abbaye Saint-Pierre et Mont Blandin", lat: 51.04642, lng: 3.72883, audio: "audio/Abbaye_Saint_Pierre_et_Mont_Blandin.mp3", image: "images/points interets/abbaye-saint-pierre-et-mont-blandin.jpg", fallbackImage: "images/points interets/Abbaye_Saint_Pierre_et_Mont_Blandin.svg" },
    { name: "Ancien béguinage Sainte-Élisabeth", lat: 51.05922, lng: 3.71082, audio: "audio/Ancien_beguinage_Sainte_Elisabeth.mp3", image: "images/points interets/ancien-beguinage-sainte-elisabeth.jpg", fallbackImage: "images/points interets/Ancien_beguinage_Sainte_Elisabeth.svg" },
    { name: "Rabot", lat: 51.06102, lng: 3.70861, audio: "audio/Rabot.mp3", image: "images/points interets/rabot.jpg", fallbackImage: "images/points interets/Rabot.svg" },
    { name: "Ruines de l’abbaye Saint-Bavon", lat: 51.05649, lng: 3.7395, audio: "audio/Ruines_de_l_abbaye_Saint_Bavon.mp3", image: "images/points interets/ruines-de-labbaye-saint-bavon.jpg", fallbackImage: "images/points interets/Ruines_de_l_abbaye_Saint_Bavon.svg" }
];
const availableCircuits=["petit","moyen","grand"];
const circuits={"petit":[1,2,3,4,5,6,7,8,1],"petit_gare":[1,2,3,4,5,6,7,8,1],"moyen":[9,10,1,2,3,11,4,5,6,7,12,13,8,14,9],"moyen_gare":[9,10,1,2,3,11,4,5,6,7,12,13,8,14,9],"grand":[15,16,17,9,10,1,2,3,11,4,5,6,7,18,19,12,13,8,14,20,15],"grand_gare":[15,16,17,9,10,1,2,3,11,4,5,6,7,18,19,12,13,8,14,20,15]};
const circuitEstimates={"petit":{"distanceKm":2.2,"walkingTimeMinutes":29,"listeningTimeMinutes":56,"totalTimeMinutes":85},"moyen":{"distanceKm":4.4,"walkingTimeMinutes":58,"listeningTimeMinutes":98,"totalTimeMinutes":156},"grand":{"distanceKm":13.1,"walkingTimeMinutes":174,"listeningTimeMinutes":140,"totalTimeMinutes":314}};
